[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
# The `g("*", p.sub)` part is intended to enable open routes when `*` used as subject in `g` csv line
m = (g(r.sub, p.sub) || g("*", p.sub)) && r.obj == p.obj && r.act == p.act
